version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew shadowJar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/tweet-analyzer-loader-2.0.0.RELEASE-aws.jar
  discard-paths: yes
