spring:
  main:
    log-startup-info: false # 起動時ログの出力停止
    banner-mode: off # 起動時のバナー表示の停止
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    password: ${DB_PASS}
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_URL}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
